# Generated by Django 3.2.13 on 2023-09-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coisasEssencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=30)),
                ('artefato', models.CharField(max_length=50)),
                ('importancia', models.CharField(choices=[('M', 'muito'), ('R', 'medio'), ('P', 'pouco')], max_length=1)),
                ('preco', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('continente', models.CharField(max_length=30)),
                ('clima', models.CharField(max_length=20)),
            ],
        ),
    ]
